version: '3.8'

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  lumenmysql:
    driver: local
  lumenmongo:
    driver: local

services:

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: php
    restart: unless-stopped
    environment:
      XDEBUG_CONFIG: 1
      PHP_IDE_CONFIG: "serverName=homestead"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: 1
      XDEBUG_IDEKEY: "PHPSTORM"
    networks:
      - app-network
    volumes:
      - ./:/var/www
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    volumes:
      - lumenmongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: p4ss
    ports:
      - 27017:27017
    networks:
      - app-network

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: p4ss
      ME_CONFIG_MONGODB_URL: mongodb://user:p4ss@mongo:27017/
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - lumenmysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: user
      MYSQL_PASSWORD: p4ss
      MYSQL_DATABASE: lumen-test
    ports:
      - 33006:3306
    networks:
      - app-network

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
