parameters:
  debug: '%env(bool:APP_DEBUG)%'

  # doctrine
  doctrine.connection:
    driver: '%env(DB_DRIVER)%'
    host: '%env(DB_HOST)%'
    port: '%env(DB_PORT)%'
    user: '%env(DB_USERNAME)%'
    password: '%env(DB_PASSWORD)%'
    dbname: '%env(DB_DATABASE)%'
  doctrine.entities_mapping: # array of: 'path from project root dir' => 'namespace'
    app/Infrastructure/Product/Model/Mappings: 'App\Domain\Product\Model'
  doctrine.custom_type_mappings: # array of: 'name' => 'namespace'
    uuid: 'App\Infrastructure\Core\ValueObject\CustomMappingType\UuidType'
    productname: 'App\Infrastructure\Product\ValueObject\CustomMappingType\ProductNameType'
    price: 'App\Infrastructure\Core\ValueObject\CustomMappingType\PriceType'

  # tactician
  tactician.mappings:
    App\Application\Product\Query\GetProductQuery: 'App\Application\Product\Query\GetProductQueryHandler'
    App\Application\Product\Command\CreateProductCommand: 'App\Application\Product\Command\CreateProductCommandHandler'

services:
  # container builder
  container_builder:
    synthetic: true # must be injected manually after instance the object

  # doctrine
  App\Infrastructure\Core\Factory\DoctrineEntityManagerFactory:
    class: App\Infrastructure\Core\Factory\DoctrineEntityManagerFactory
    arguments:
      - '%doctrine.connection%'
      - '%doctrine.entities_mapping%'
      - '%doctrine.custom_type_mappings%'
      - '%debug%'
    public: true # make it public to be used directly in doctrine migrations

  Doctrine\ORM\EntityManager:
    class: Doctrine\ORM\EntityManager
    factory:
      - '@App\Infrastructure\Core\Factory\DoctrineEntityManagerFactory'
      - create

  # tactician
  App\Infrastructure\Core\Factory\TacticianCommandHandlerMiddlewareFactory:
    class: App\Infrastructure\Core\Factory\TacticianCommandHandlerMiddlewareFactory
    arguments:
      - '@container_builder'
      - '%tactician.mappings%'

  League\Tactician\Handler\CommandHandlerMiddleware:
    class: League\Tactician\Handler\CommandHandlerMiddleware
    factory:
      - '@App\Infrastructure\Core\Factory\TacticianCommandHandlerMiddlewareFactory'
      - create

  App\Infrastructure\Core\Factory\DoctrineTransactionMiddlewareFactory:
    class: App\Infrastructure\Core\Factory\DoctrineTransactionMiddlewareFactory
    arguments:
      - '@Doctrine\ORM\EntityManager'

  App\Infrastructure\Core\Bus\DoctrineTransactionMiddleware:
    class: App\Infrastructure\Core\Bus\DoctrineTransactionMiddleware
    factory:
      - '@App\Infrastructure\Core\Factory\DoctrineTransactionMiddlewareFactory'
      - create

  App\Infrastructure\Core\Factory\CommandBusFactory:
    class: App\Infrastructure\Core\Factory\CommandBusFactory
    arguments:
      - [ '@App\Infrastructure\Core\Bus\DoctrineTransactionMiddleware', '@League\Tactician\Handler\CommandHandlerMiddleware' ]

  App\Infrastructure\Core\Bus\CommandBus:
    class: App\Infrastructure\Core\Bus\CommandBus
    factory:
      - '@App\Infrastructure\Core\Factory\CommandBusFactory'
      - create
    public: true # make it public to be used directly in bootstrap/app.php

  App\Infrastructure\Core\Factory\QueryBusFactory:
    class: App\Infrastructure\Core\Factory\QueryBusFactory
    arguments:
      - [ '@League\Tactician\Handler\CommandHandlerMiddleware' ]

  App\Infrastructure\Core\Bus\QueryBus:
    class: App\Infrastructure\Core\Bus\QueryBus
    factory:
      - '@App\Infrastructure\Core\Factory\QueryBusFactory'
      - create
    public: true # make it public to be used directly in bootstrap/app.php

  # services
  App\Infrastructure\Core\Service\RamseyUuidGenerator:
    class: App\Infrastructure\Core\Service\RamseyUuidGenerator
