parameters:
  example_parameter: 'EXAMPLE'

services:
  App\Application\Product\Query\GetProductQueryHandler:
    class: App\Application\Product\Query\GetProductQueryHandler
    arguments:
      - '@App\Infrastructure\Product\Repository\RandomPokemonProductRepository'
    tags:
      - { name: tactician.handler, typehints: true }

  App\Infrastructure\Product\Repository\RandomProductRepository:
    class: App\Infrastructure\Product\Repository\RandomProductRepository

  App\Infrastructure\Product\Repository\RandomPokemonProductRepository:
    class: App\Infrastructure\Product\Repository\RandomPokemonProductRepository
