services:
  # query handlers
  App\Application\Product\Query\GetProductQueryHandler:
    arguments:
      - '@App\Domain\Product\Service\ProductFinder'
    public: true
    tags:
      - { name: tactician.handler, typehints: true }
  App\Application\Product\Query\GetProductsQueryHandler:
    arguments:
      - '@App\Domain\Product\Service\ProductFinder'
    public: true
    tags:
      - { name: tactician.handler, typehints: true }

  # command handlers
  App\Application\Product\Command\CreateProductCommandHandler:
    arguments:
      - '@App\Domain\Product\Builder\ProductBuilder'
      - '@App\Infrastructure\Product\Repository\DocumentManagerProductRepository'
      - '@App\Infrastructure\Core\Event\LumenEventDispatcher'
    public: true
    tags:
      - { name: tactician.handler, typehints: true }
  App\Application\Product\Command\UpdateProductCommandHandler:
    arguments:
      - '@App\Domain\Product\Builder\ProductUpdater'
      - '@App\Infrastructure\Product\Repository\DocumentManagerProductRepository'
      - '@App\Infrastructure\Core\Event\LumenEventDispatcher'
    public: true
    tags:
      - { name: tactician.handler, typehints: true }

  # listeners
  App\Application\Product\Listener\SaveProductOnAlternativeStorageListener:
    arguments:
      - '@App\Infrastructure\Product\Repository\EntityManagerProductRepository'
      - '@App\Domain\Product\Service\ProductFinder'
      - '@App\Infrastructure\Core\Service\LumenLogger'
    public: true

  # services
  App\Domain\Product\Builder\ProductBuilder:
    arguments:
      - '@App\Infrastructure\Core\Service\RamseyUuidGenerator'
  App\Domain\Product\Builder\ProductUpdater:
    arguments:
      - '@App\Infrastructure\Product\Repository\DocumentManagerProductRepository'

  App\Domain\Product\Service\ProductFinder:
    arguments:
      - '@App\Infrastructure\Product\Repository\DocumentManagerProductRepository'

  # repositories
  App\Infrastructure\Product\Repository\RandomPokemonProductRepository:

  App\Infrastructure\Product\Repository\VoidProductRepository:

  App\Infrastructure\Product\Repository\EntityManagerProductRepository:
    arguments:
      - '@Doctrine\ORM\EntityManager'

  App\Infrastructure\Product\Repository\DocumentManagerProductRepository:
    arguments:
      - '@Doctrine\ODM\MongoDB\DocumentManager'
