parameters:
  debug: '%env(bool:APP_DEBUG)%'
  # doctrine
  doctrine.connection:
    driver: '%env(DB_DRIVER)%'
    host: '%env(DB_HOST)%'
    port: '%env(DB_PORT)%'
    user: '%env(DB_USERNAME)%'
    password: '%env(DB_PASSWORD)%'
    dbname: '%env(DB_DATABASE)%'
  doctrine.entities_mapping: # array of: 'path from project root dir' => 'namespace'
    app/Infrastructure/Product/Model/Mappings: 'App\Domain\Product\Model'
  doctrine.custom_type_mappings: # array of: 'name' => 'namespace'
    uuid: 'App\Infrastructure\Core\ValueObject\CustomMappingType\UuidType'
    productname: 'App\Infrastructure\Product\ValueObject\CustomMappingType\ProductNameType'
    price: 'App\Infrastructure\Core\ValueObject\CustomMappingType\PriceType'

services:
  # services
  App\Infrastructure\Core\Service\RamseyUuidGenerator:
    class: App\Infrastructure\Core\Service\RamseyUuidGenerator

  # doctrine
  App\Infrastructure\Core\Factory\DoctrineEntityManagerFactory:
    class: App\Infrastructure\Core\Factory\DoctrineEntityManagerFactory
    arguments:
      - '%doctrine.connection%'
      - '%doctrine.entities_mapping%'
      - '%doctrine.custom_type_mappings%'
      - '%debug%'
    public: true # make the container public to be used directly in doctrine migrations

  Doctrine\ORM\EntityManager:
    class: Doctrine\ORM\EntityManager
    factory:
      - '@App\Infrastructure\Core\Factory\DoctrineEntityManagerFactory'
      - create
